name: Python Pull Request Workflow
on: [pull_request]
jobs:

  qa:
    name: Quality check
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.8
      - name: Run unit tests
        run: |
          pip install pytest
          pytest
      - name: Wemake Python Stylguide
        uses: wemake-services/wemake-python-styleguide@0.13.4
        continue-on-error: true
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#    docker-build:
#      runs-on: ubuntu-latest
#      steps:
#        - uses: actions/checkout@v2
#
#        - name: Build docker image
#          run: docker build . -t project_name
#
#        - name: Test image
#          run: |
#            docker run --rm -d --name test_container -p 8000:8000 project_name
#            docker run --link test_container:test_container waisbrot/wait
#            curl --fail http://localhost:8000